version: "3.8"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: rust-backend
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
    env_file:
      - ./api/.env
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - CASSANDRA_HOST=cassandra-db:9042

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend

  cassandra:
    image: cassandra:4.1
    container_name: cassandra-db
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
  game:
    build:
      context: ./game
      dockerfile: Dockerfile
    container_name: game-server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
volumes:
  cassandra-data:
