name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ./kerek
            git checkout main
            git fetch
            git pull
            cat > ./frontend/.env <<EOF
            NEXT_PUBLIC_API_URL=https://kerek.club/api
            API_URL=http://rust-backend:8080/api
            NEXT_PUBLIC_WS_URL=wss://kerek.club
            NEXT_PUBLIC_GIPHY_API_KEY=${{ secrets.NEXT_PUBLIC_GIPHY_API_KEY }}
            CLOUDFLARE_R2_ACCESS_KEY_ID=${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
            CLOUDFLARE_R2_SECRET_ACCESS_KEY=${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
            CLOUDFLARE_R2_BUCKET_NAME=kerek
            CLOUDFLARE_R2_ENDPOINT=${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
            NEXT_PUBLIC_CLOUDFLARE_R2_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_CLOUDFLARE_R2_PUBLIC_URL }}
            EOF
            chmod 600 ./frontend/.env
            cd ..
            cd ./api
            cat > ./api/.env <<EOF
            HOST=0.0.0.0
            PORT=8080
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            CASSANDRA_HOST=cassandra-db:9042
            EOF
            chmod 600 ./api/.env

            cd ./kerek
            docker compose up -d --build
